db_name: kwb_dw
schema_name: pge

s3:
  bucket: kwb-crl-bucket
  webhook_prefix: pge/webhooks/unprocessed/
  archive_prefix: pge/webhooks/processed/

sources:
  - name: pge_daily_energy_usage
    table_name: fact_daily_energy_usage
    dbt_models: stg_pge__fact_daily_energy_usage+
    prim_key: 
      - usage_point_id
      - start_time
    update_cols:
      - value
      - time_of_use
    schema:
      - json_field: usage_point
        db_field: usage_point_id
        dtype: string
      - json_field: reading_quality
        db_field: reading_quality
        dtype: string
      - json_field: duration
        db_field: duration
        dtype: int
      - json_field: start
        db_field: start_time
        dtype: timestamp 
      - json_field: value
        db_field: value
        dtype: float64
      - json_field: tou
        db_field: time_of_use
        dtype: string
      - json_field: unit
        db_field: unit
        dtype: string       

